language: perl
sudo:     false

addons:
  apt:
      - libluajit-5.1-2
      - libluajit-5.1-dev

env:
  global:
    - LUAJIT_LIB=/usr/lib/x86_64-linux-gnu/
    - LUAJIT_INC=/usr/include/luajit-2.0/
    - VER_LUA_NGINX=0.9.19
    - VER_NGX_DEVEL=0.2.19
    - VER_NGINX=1.9.7

install: cpanm -v --notest Test::Nginx
script:  ./compile_and_test.sh
